disabled_rules:
  - cyclomatic_complexity
  - type_name
  - function_parameter_count
  - unused_optional_binding
  - unused_closure_parameter
  - large_tuple
  - array_init
  - multiple_closures_with_trailing_closure
  - implicit_getter
  - trailing_whitespace
  - conditional_returns_on_newline

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - first_where
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - unneeded_parentheses_in_closure_argument

excluded:
  - Sources/adapto-ios-package/OpenAPIs

shorthand_operator:
  severity: warning

force_cast:
  severity: error

force_try:
  severity: error

line_length:
  warning: 100
  error: 200

file_length:
  warning: 1000
  error: 1300

identifier_name:
  severity: warning
  min_length:
    warning: 2
  max_length:
    warning: 60
  validates_start_with_lowercase: true
  excluded:
    - x
    - y
    - z
    - q
    - id
    - URL
    - Map

reporter: "xcode"

nesting:
  type_level:
    warning: 2
    error: 4
  statement_level: 6

type_body_length:
  warning: 650
  error: 800

function_body_length:
  warning: 300
  error: 400
