name: Auto Commenbt
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            @{{ author }} opened pr
            checklist:
            - [ ] Tests geschreven
            - [ ] Tests uitgevoerd
